apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mcombi-poi-backend-app-dev
  annotations:
    argocd/app-name: mcombi-poi-backend-app-dev
    backstage.io/kubernetes-id: mcombi-poi-backend-app-dev
    backstage.io/kubernetes-namespace: mcombi
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=mcombi-poi-backend-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23JanusN/mcombi-backend
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/mcombi/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/k8s/ns/mcombi/deployments/poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23bis.17gd.p1.openshiftapps.com/#https://github.com/Summit23JanusN/mcombi-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:mcombi"
  system: workshop-system-mcombi
  providesApis:
    - backend-api-mcombi
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-mcombi
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:mcombi"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-mcombi
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://poi-backend-app-mcombi.apps.summit23bis.17gd.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23JanusN/mcombi-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:mcombi"
  system: workshop-system-mcombi
  definition:
    $text: https://github.com/Summit23JanusN/mcombi-backend/tree/main/src/main/resources/META-INF/openapi.yaml
